import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./vp.css";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const validThemes: string[] = [
    '',
    'amethyst-haze',
    'claymorphism',
    'darkmatter',
    'default',
    'mono',
    'northern-lights',
    'notebook',
    'solar-dusk',
    'supabase',
    'violet-bloom',
  ].reduce((prev, curr) => {
    prev.push(curr + '-light', curr + '-dark');
    return prev;
  }, [] as string[]).map(i => i.replace(/^-/g, ''))
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          themes={validThemes}
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
