name: Build and Release VideoPlayerNext Binary

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0 
  workflow_dispatch:

jobs:
  build-next:
    name: Build Next.js
    runs-on: ubuntu-latest

    steps:
      - name: Checokout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Install dependencies
        run: |
          cd fe
          npm ci


      - name: Build with Next.js
        run: |
          cd fe
          export DIST_DIR="../be/cmd/serve/website"
          export MODE="prod"
          npm run build


  build-go:
    name: Build Go
    runs-on: ubuntu-latest
    needs: build-next

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
 
      - name: Build Binary
        run: |
          cd be
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/video-player-linux-amd64 .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
